name: flutter_date_picker
description: Cupertino styled date picker component which works on both ios and android.
version: 0.1.3
author: Rajesh Kumar <rajesh.kumar@highpeaksw.com>
homepage: https://github.com/rajeshzmoke/flutter_date_picker

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=1.19.0 <3.0.0"
  flutter: ">=0.4.1 <1.0.0"
